export const FETCH_MESSAGE_REQUESTS = "FETCH_MESSAGE_REQUESTS"
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS"
export const FETCH_MESSAGE_FAILURE = "FETCH_MESSAGE_FAILURE"

export const SEND_MESSAGE_REQUESTS = "SEND_MESSAGE_REQUESTS"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE"

export const FETCH_CHAT_BY_PROJECT_REQUESTS = "FETCH_CHAT_BY_PROJECT_REQUESTS"
export const FETCH_CHAT_BY_PROJECT_SUCCESS = "FETCH_CHAT_BY_PROJECT_SUCCESS"
export const FETCH_CHAT_BY_PROJECT_FAILURE = "FETCH_CHAT_BY_PROJECT_FAILURE"

export const FETCH_CHAT_MESSAGE_REQUESTS = "FETCH_CHAT_MESSAGE_REQUESTS"
export const FETCH_CHAT_MESSAGE_SUCCESS = "FETCH_CHAT_MESSAGE_SUCCESS"
export const FETCH_CHAT_MESSAGE_FAILURE = "FETCH_CHAT_MESSAGE_FAILURE"
 