export const FETCH_ISSUE_REQUESTS = "FETCH_ISSUE_REQUESTS"
export const FETCH_ISSUE_SUCCESS = "FETCH_ISSUE_SUCCESS"
export const FETCH_ISSUE_FAILURE = "FETCH_ISSUE_FAILURE"

export const FETCH_ISSUE_BY_ID_REQUESTS = "FETCH_ISSUE_BY_ID_REQUESTS"
export const FETCH_ISSUE_BY_ID_SUCCESS = "FETCH_ISSUE_BY_ID_SUCCESS"
export const FETCH_ISSUE_BY_ID_FAILURE = "FETCH_ISSUE_BY_ID_FAILURE"

export const CREATE_ISSUE_REQUESTS = "CREATE_ISSUE_REQUESTS"
export const CREATE_ISSUE_SUCCESS = "CREATE_ISSUE_SUCCESS"
export const CREATE_ISSUE_FAILURE = "CREATE_ISSUE_FAILURE"


export const UDPATE_ISSUE_STATUS_REQUESTS = "UDPATE_ISSUE_STATUS_REQUESTS"
export const UDPATE_ISSUE_STATUS_SUCCESS = "UDPATE_ISSUE_STATUS_SUCCESS"
export const UDPATE_ISSUE_STATUS_FAILURE = "UDPATE_ISSUE_STATUS_FAILURE"
 
export const DELETE_ISSUE_REQUESTS = "DELETE_ISSUE_REQUESTS"
export const DELETE_ISSUE_SUCCESS = "DELETE_ISSUE_SUCCESS"
export const DELETE_ISSUE_FAILURE = "DELETE_ISSUE_FAILURE"

export const ASSIGNED_ISSUE_TO_USER_REQUESTS = "ASSIGNED_ISSUE_TO_USER_REQUESTS"
export const ASSIGNED_ISSUE_TO_USER_SUCCESS = "ASSIGNED_ISSUE_TO_USER_SUCCESS"
export const ASSIGNED_ISSUE_TO_USER_FAILURE = "ASSIGNED_ISSUE_TO_USER_FAILURE"